version: "3.9"

services:
  auth-service:
    container_name: auth-service
    build: 
      context: .
      dockerfile: Dockerfile
      target: auth-service
    ports:
      - "50051:50051"
    environment:
      - SQLITE_DSN=./users.db
    networks:
      - webnet
    depends_on:
      - redis-pms
      
  redis-pms:
    image: redis:7.0.8
    container_name: "redis-pms"
    restart: "always"
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - "redis-server"
    networks:
      - webnet

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - webnet

networks:
  webnet: