version: "3.9"

services:
  redis:
    image: redis:7.0.8
    container_name: "redis"
    restart: "always"
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - "redis-server"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
      - 15672:15672